-- return {
--   -- Git Hub Copilot chat
--   {
--     "CopilotC-Nvim/CopilotChat.nvim",
--     event = "VeryLazy",
--     dependencies = {
--       { "github/copilot.vim" }, -- or zbirenbaum/copilot.lua
--       { "nvim-lua/plenary.nvim", branch = "master" }, -- for curl, log and async functions
--     },
--     build = "make tiktoken", -- OnVirticle split vsp ly on MacOS or Linux
--     opts = {
--       -- See Configuration section for options
--     },
--     -- See Commands section for default commands if you want to lazy load on them
--     keys = {
--       { "<leader>zc", ":CopilotChat<CR>", mode = { "n", "v" }, desc = "Copilot Chat" },
--       { "<leader>ze", ":CopilotChatExplain<CR>", mode = { "v" }, desc = "Explain Code" },
--       { "<leader>zr", ":CopilotChatReview<CR>", mode = { "v" }, desc = "Review Code" },
--       { "<leader>zf", ":CopilotChatFix<CR>", mode = { "v" }, desc = "Fix Code Issues" },
--       { "<leader>zo", ":CopilotChatDocs<CR>", mode = { "v" }, desc = "Generate Docs" },
--       { "<leader>zd", ":CopilotChatTests<CR>", mode = { "v" }, desc = "Generate Tests" },
--       { "<leader>zt", ":CopilotChatTest<CR>", mode = { "v" }, desc = "Generate Test" },
--       { "<leader>zm", ":CopilotChatCommit<CR>", mode = { "n" }, desc = "Generate Commit message" },
--       { "<leader>zs", ":CopilotChatCommit<CR>", mode = { "v" }, desc = "Generate commit for selection" },
--     },
--   },
-- }
